CREATE TABLE IF NOT EXISTS photo
(
    pid SERIAL PRIMARY KEY NOT NULL,
    url VARCHAR(200) NOT NULL,
    title VARCHAR(100) DEFAULT 'Untitled',
    uid INTEGER NOT NULL,
    datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tag
(
    tid INTEGER NOT NULL,
    pid INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tag_alias
(
    alias_id SERIAL PRIMARY KEY NOT NULL,
    old_name VARCHAR(50) NOT NULL,
    new_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tag_imp
(
    imp_id SERIAL PRIMARY KEY NOT NULL,
    predicate VARCHAR(50),
    implies VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS tag_ref
(
    tid SERIAL PRIMARY KEY NOT NULL,
    tag_name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS users
(
    uid SERIAL PRIMARY KEY NOT NULL,
    uname VARCHAR(50),
    email VARCHAR(200),
    phone INTEGER,
    avatar VARCHAR(200),
    upload_count INTEGER,
    created_date DATE DEFAULT CURRENT_DATE
);